/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/yarn/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get yarn by ID */
        get: operations["getYarnById"];
        /** Update yarn */
        put: operations["updateYarn"];
        post?: never;
        /** Delete yarn */
        delete: operations["deleteYarn"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/yarn/{id}/folder/{folderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Move yarn to folder */
        put: operations["moveToFolder"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/yarns/{yarnId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateYarn_1"];
        post?: never;
        delete: operations["removeYarn"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findById"];
        put: operations["update"];
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patterns/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findById_1"];
        put: operations["update_1"];
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/folder/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get folder by ID */
        get: operations["getFolderById"];
        /** Update folder */
        put: operations["updateFolder"];
        post?: never;
        /** Delete folder */
        delete: operations["deleteFolder"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register new user */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token using refresh token cookie */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout and clear authentication cookies */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with cookie-based authentication */
        post: operations["authenticate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/yarn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all yarn */
        get: operations["getAllYarn"];
        put?: never;
        /** Create new yarn */
        post: operations["createYarn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/yarns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getYarns"];
        put?: never;
        post: operations["addYarn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patterns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll_1"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/folder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all folders */
        get: operations["getAllFolders"];
        put?: never;
        /** Create new folder */
        post: operations["createFolder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/yarn/{id}/folder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove yarn from folder */
        delete: operations["removeFromFolder"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        YarnRequest: {
            name: string;
            brand: string;
            color?: string;
            /** @enum {string} */
            category?: "LACE" | "LIGHT_FINGERING" | "FINGERING" | "SPORT" | "DK" | "WORSTED" | "ARAN" | "BULKY" | "SUPER_BULKY" | "JUMBO";
            /** Format: int32 */
            weightInGrams?: number;
            /** Format: int32 */
            lengthInMeters?: number;
            fiberContent?: string;
            /** Format: int32 */
            quantity?: number;
            /** Format: int32 */
            folderId?: number;
            pricePerUnit?: number;
            currencyCode?: string;
        };
        YarnResponse: {
            /** Format: int32 */
            id?: number;
            name?: string;
            brand?: string;
            color?: string;
            /** @enum {string} */
            category?: "LACE" | "LIGHT_FINGERING" | "FINGERING" | "SPORT" | "DK" | "WORSTED" | "ARAN" | "BULKY" | "SUPER_BULKY" | "JUMBO";
            /** Format: int32 */
            weightInGrams?: number;
            /** Format: int32 */
            lengthInMeters?: number;
            fiberContent?: string;
            /** Format: int32 */
            quantity?: number;
            /** Format: int32 */
            folderId?: number;
            folderName?: string;
            pricePerUnit?: number;
            currencyCode?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ProjectYarnRequest: {
            /** Format: int32 */
            yarnId: number;
            quantityNeeded?: number;
            quantityUsed?: number;
            notes?: string;
        };
        ProjectYarnResponse: {
            /** Format: int32 */
            id?: number;
            yarn?: components["schemas"]["YarnSummary"];
            quantityNeeded?: number;
            quantityUsed?: number;
            notes?: string;
            lineCost?: number;
        };
        YarnSummary: {
            /** Format: int32 */
            id?: number;
            name?: string;
            brand?: string;
            color?: string;
            pricePerUnit?: number;
            currencyCode?: string;
        };
        ProjectRequest: {
            name: string;
            /** @enum {string} */
            status: "PLANNED" | "WIP" | "COMPLETED" | "FROGGED";
            notes?: string;
            tools?: string;
            imageUrl?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            completionDate?: string;
            /** Format: int32 */
            patternId?: number;
        };
        PatternSummary: {
            /** Format: int32 */
            id?: number;
            name?: string;
            designer?: string;
            /** @enum {string} */
            difficulty?: "BEGINNER" | "INTERMEDIATE" | "ADVANCED";
        };
        ProjectResponse: {
            /** Format: int32 */
            id?: number;
            name?: string;
            /** @enum {string} */
            status?: "PLANNED" | "WIP" | "COMPLETED" | "FROGGED";
            notes?: string;
            tools?: string;
            imageUrl?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            completionDate?: string;
            pattern?: components["schemas"]["PatternSummary"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        PatternRequest: {
            name: string;
            designer?: string;
            sourceUrl?: string;
            /** @enum {string} */
            difficulty?: "BEGINNER" | "INTERMEDIATE" | "ADVANCED";
            notes?: string;
        };
        PatternResponse: {
            /** Format: int32 */
            id?: number;
            name?: string;
            designer?: string;
            sourceUrl?: string;
            /** @enum {string} */
            difficulty?: "BEGINNER" | "INTERMEDIATE" | "ADVANCED";
            notes?: string;
            /** Format: int32 */
            projectCount?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        FolderRequest: {
            name: string;
            description?: string;
        };
        FolderResponse: {
            /** Format: int32 */
            id?: number;
            name?: string;
            description?: string;
            /** Format: int32 */
            yarnCount?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        SignUpRequest: {
            fullName: string;
            email: string;
            password: string;
            /** @enum {string} */
            role?: "ADMIN" | "USER" | "MODERATOR";
        };
        Folder: {
            /** Format: int32 */
            id?: number;
            name?: string;
            description?: string;
            user?: components["schemas"]["User"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            yarns?: components["schemas"]["Yarn"][];
        };
        GrantedAuthority: {
            authority?: string;
        };
        User: {
            /** Format: int32 */
            id?: number;
            fullName?: string;
            email?: string;
            password?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** @enum {string} */
            role?: "ADMIN" | "USER" | "MODERATOR";
            yarns?: components["schemas"]["Yarn"][];
            folders?: components["schemas"]["Folder"][];
            enabled?: boolean;
            username?: string;
            authorities?: components["schemas"]["GrantedAuthority"][];
            accountNonLocked?: boolean;
            credentialsNonExpired?: boolean;
            accountNonExpired?: boolean;
        };
        Yarn: {
            /** Format: int32 */
            id?: number;
            name?: string;
            brand?: string;
            color?: string;
            /** @enum {string} */
            category?: "LACE" | "LIGHT_FINGERING" | "FINGERING" | "SPORT" | "DK" | "WORSTED" | "ARAN" | "BULKY" | "SUPER_BULKY" | "JUMBO";
            /** Format: int32 */
            weightInGrams?: number;
            /** Format: int32 */
            lengthInMeters?: number;
            fiberContent?: string;
            /** Format: int32 */
            quantity?: number;
            pricePerUnit?: number;
            currencyCode?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            user?: components["schemas"]["User"];
            folder?: components["schemas"]["Folder"];
        };
        AuthResponse: {
            success?: boolean;
            message?: string;
            user?: components["schemas"]["UserResponse"];
        };
        UserResponse: {
            /** Format: int32 */
            id?: number;
            fullName?: string;
            email?: string;
            /** @enum {string} */
            role?: "ADMIN" | "USER" | "MODERATOR";
            /** Format: date-time */
            createdAt?: string;
        };
        SignInRequest: {
            email: string;
            password: string;
        };
        ProjectCostResponse: {
            /** Format: int32 */
            projectId?: number;
            projectName?: string;
            totalCost?: number;
            currencyWarning?: string;
            yarnCosts?: components["schemas"]["ProjectYarnCost"][];
        };
        ProjectYarnCost: {
            /** Format: int32 */
            yarnId?: number;
            yarnName?: string;
            pricePerUnit?: number;
            currencyCode?: string;
            quantity?: number;
            lineCost?: number;
        };
        FolderDetailResponse: {
            /** Format: int32 */
            id?: number;
            name?: string;
            description?: string;
            yarns?: components["schemas"]["YarnResponse"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getYarnById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved yarn */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["YarnResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["YarnResponse"];
                };
            };
            /** @description Yarn not found or not owned by user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["YarnResponse"];
                };
            };
        };
    };
    updateYarn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["YarnRequest"];
            };
        };
        responses: {
            /** @description Yarn updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["YarnResponse"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["YarnResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["YarnResponse"];
                };
            };
            /** @description Yarn not found or not owned by user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["YarnResponse"];
                };
            };
        };
    };
    deleteYarn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Yarn deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Yarn not found or not owned by user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    moveToFolder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                folderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Yarn moved to folder successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["YarnResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["YarnResponse"];
                };
            };
            /** @description Yarn or folder not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["YarnResponse"];
                };
            };
        };
    };
    updateYarn_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                yarnId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectYarnRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectYarnResponse"];
                };
            };
        };
    };
    removeYarn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                yarnId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findById_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PatternResponse"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatternRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PatternResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFolderById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved folder */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FolderDetailResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FolderDetailResponse"];
                };
            };
            /** @description Folder not found or not owned by user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FolderDetailResponse"];
                };
            };
        };
    };
    updateFolder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderRequest"];
            };
        };
        responses: {
            /** @description Folder updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FolderResponse"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FolderResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FolderResponse"];
                };
            };
            /** @description Folder not found or not owned by user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FolderResponse"];
                };
            };
            /** @description Folder with new name already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FolderResponse"];
                };
            };
        };
    };
    deleteFolder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Folder deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Folder not found or not owned by user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpRequest"];
            };
        };
        responses: {
            /** @description User registered successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
            /** @description User with this email already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token refreshed successfully, new access token cookie set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid or missing refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully, cookies cleared */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    authenticate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInRequest"];
            };
        };
        responses: {
            /** @description Login successful, access and refresh token cookies set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    getAllYarn: {
        parameters: {
            query?: {
                category?: "LACE" | "LIGHT_FINGERING" | "FINGERING" | "SPORT" | "DK" | "WORSTED" | "ARAN" | "BULKY" | "SUPER_BULKY" | "JUMBO";
                folderId?: number;
                unsorted?: boolean;
                brand?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved yarn list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["YarnResponse"][];
                };
            };
            /** @description Unauthorized - Invalid or missing JWT token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["YarnResponse"][];
                };
            };
        };
    };
    createYarn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["YarnRequest"];
            };
        };
        responses: {
            /** @description Yarn created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["YarnResponse"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["YarnResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["YarnResponse"];
                };
            };
        };
    };
    findAll: {
        parameters: {
            query?: {
                status?: "PLANNED" | "WIP" | "COMPLETED" | "FROGGED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectResponse"];
                };
            };
        };
    };
    getYarns: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectYarnResponse"][];
                };
            };
        };
    };
    addYarn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectYarnRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectYarnResponse"];
                };
            };
        };
    };
    findAll_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PatternResponse"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatternRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PatternResponse"];
                };
            };
        };
    };
    getAllFolders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved folder list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FolderResponse"][];
                };
            };
            /** @description Unauthorized - Invalid or missing JWT token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FolderResponse"][];
                };
            };
        };
    };
    createFolder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderRequest"];
            };
        };
        responses: {
            /** @description Folder created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FolderResponse"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FolderResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FolderResponse"];
                };
            };
            /** @description Folder with this name already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FolderResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User data returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    getCost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectCostResponse"];
                };
            };
        };
    };
    removeFromFolder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Yarn removed from folder successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["YarnResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["YarnResponse"];
                };
            };
            /** @description Yarn not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["YarnResponse"];
                };
            };
        };
    };
}
